@echo off
REM ============================================================
REM SAR Narrative Generator — Windows Setup Script
REM ============================================================
REM Usage:    setup.bat [role]
REM
REM Roles:
REM   shubh   - Core + Backend (FastAPI, SQLAlchemy, PostgreSQL)
REM   dev     - Core + LLM/RAG (LangChain, ChromaDB, Ollama client)
REM   siddh   - Core only (Streamlit frontend)
REM   het     - Core + ML (XGBoost, scikit-learn, SHAP)
REM   sakshi  - Nothing to install (docs only)
REM   all     - Everything except Ollama model
REM ============================================================

setlocal enabledelayedexpansion

set ROLE=%1
if "%ROLE%"=="" set ROLE=shubh
set VENV_DIR=.venv
set LOG_DIR=setup_logs
set LOG_FILE=%LOG_DIR%\%ROLE%_installed.md

echo.
echo === SAR Narrative Generator — Setup ===
echo Role: %ROLE%
echo.

REM --- Step 1: Create venv ---
if not exist "%VENV_DIR%" (
    echo Creating virtual environment...
    python -m venv %VENV_DIR%
    echo Virtual environment created at %VENV_DIR%\
) else (
    echo Virtual environment already exists at %VENV_DIR%\
)

REM Activate
call %VENV_DIR%\Scripts\activate.bat

REM --- Step 2: Upgrade pip ---
echo.
echo Upgrading pip...
pip install --upgrade pip -q

REM --- Step 3: Install core packages ---
echo.
echo Installing core packages (Streamlit + FastAPI + Pandas)...
pip install streamlit fastapi uvicorn pandas plotly python-dotenv python-multipart httpx pydantic pydantic-settings networkx -q
echo Core packages installed!

REM --- Step 4: Role-specific packages ---
if "%ROLE%"=="shubh" (
    echo.
    echo Installing Shubh's packages ^(Backend + DB^)...
    pip install sqlalchemy alembic "psycopg[binary]" fpdf2 -q
    echo Backend packages installed!
)
if "%ROLE%"=="dev" (
    echo.
    echo Installing Dev's packages ^(LLM + RAG^)...
    pip install langchain langchain-community langchain-ollama chromadb ollama -q
    echo LLM/RAG packages installed!
    echo.
    echo To set up Ollama with Docker:
    echo   docker-compose up -d ollama
    echo   docker exec sargen_ollama ollama pull llama3.1:8b
)
if "%ROLE%"=="siddh" (
    echo.
    echo Siddh ^(Frontend^) — core packages are all you need!
)
if "%ROLE%"=="het" (
    echo.
    echo Installing Het's packages ^(ML + Data^)...
    pip install xgboost scikit-learn shap joblib -q
    echo ML packages installed!
)
if "%ROLE%"=="sakshi" (
    echo.
    echo Sakshi ^(Docs^) — no Python packages needed!
)
if "%ROLE%"=="all" (
    echo.
    echo Installing ALL packages...
    pip install -r backend\requirements.txt -r frontend\requirements.txt -q
    echo All packages installed!
)

REM --- Step 5: Create directories ---
echo.
echo Ensuring project directories exist...
if not exist "data\sample_data" mkdir data\sample_data
if not exist "screenshots" mkdir screenshots
if not exist "ml_models" mkdir ml_models
if not exist "backend\knowledge_base\sar_templates" mkdir backend\knowledge_base\sar_templates
if not exist "backend\knowledge_base\regulations" mkdir backend\knowledge_base\regulations
if not exist "%LOG_DIR%" mkdir %LOG_DIR%

REM --- Step 6: Copy .env ---
if not exist ".env" (
    if exist ".env.example" (
        copy .env.example .env >nul
        echo .env created from .env.example
    )
)

REM --- Step 7: Generate install log ---
echo.
echo Generating your install log...
pip freeze > %LOG_DIR%\%ROLE%_freeze.txt

echo # Install Log — %ROLE% > %LOG_FILE%
echo. >> %LOG_FILE%
echo ^> **Auto-generated by setup.bat** — do not edit manually. >> %LOG_FILE%
echo ^> Re-run `setup.bat %ROLE%` to update this file. >> %LOG_FILE%
echo. >> %LOG_FILE%
echo - **Person:** %ROLE% >> %LOG_FILE%
echo - **Setup Date:** %date% %time% >> %LOG_FILE%
echo - **Machine:** %COMPUTERNAME% >> %LOG_FILE%
echo - **OS:** Windows >> %LOG_FILE%
echo. >> %LOG_FILE%
echo ## Full Package List >> %LOG_FILE%
echo. >> %LOG_FILE%
echo ```>> %LOG_FILE%
type %LOG_DIR%\%ROLE%_freeze.txt >> %LOG_FILE%
echo ```>> %LOG_FILE%
del %LOG_DIR%\%ROLE%_freeze.txt

echo Install log saved to %LOG_FILE%

REM --- Summary ---
echo.
echo ===================================
echo Setup complete for %ROLE%!
echo ===================================
echo.
echo Your install log: %LOG_FILE%
echo.
echo To run the frontend:
echo   %VENV_DIR%\Scripts\activate.bat
echo   cd frontend ^&^& streamlit run app.py
echo.
echo To run the backend:
echo   %VENV_DIR%\Scripts\activate.bat
echo   cd backend ^&^& uvicorn app.main:app --reload --port 8000
echo.

endlocal
