"""
API Routes — SAR Narrative Generator
"""
import uuid
from fastapi import APIRouter, UploadFile, File, HTTPException
from app.api.schemas import (
    CaseData,
    SARResponse,
    SARNarrative,
    SARStatus,
    GenerateSARRequest,
    UpdateSARRequest,
    CaseListItem,
    CaseListResponse,
    AuditStep,
    QualityScore,
    RiskLevel,
)
from datetime import datetime

router = APIRouter()

# In-memory storage (will be replaced with PostgreSQL)
cases_store: dict[str, CaseData] = {}
sars_store: dict[str, SARResponse] = {}


@router.post("/upload", tags=["Data"])
async def upload_data(file: UploadFile = File(...)):
    """Upload transaction/customer data (CSV or JSON)."""
    if not file.filename.endswith((".csv", ".json")):
        raise HTTPException(status_code=400, detail="Only CSV and JSON files are supported")

    content = await file.read()
    case_id = f"CASE-{uuid.uuid4().hex[:6].upper()}"

    # TODO: Parse file content using data_parser (P4)
    # For now, store raw content
    cases_store[case_id] = {
        "case_id": case_id,
        "filename": file.filename,
        "size": len(content),
        "uploaded_at": datetime.now().isoformat(),
    }

    return {
        "case_id": case_id,
        "filename": file.filename,
        "status": "uploaded",
        "message": f"Data uploaded successfully. Case ID: {case_id}",
    }


@router.post("/generate-sar", response_model=SARResponse, tags=["SAR"])
async def generate_sar(request: GenerateSARRequest):
    """Generate a SAR narrative for a given case."""
    case_id = request.case_id

    # TODO: Integrate with P2's llm_engine.generate_sar()
    # For now, return a placeholder SAR
    sar_id = f"SAR-{uuid.uuid4().hex[:6].upper()}"

    sar = SARResponse(
        sar_id=sar_id,
        case_id=case_id,
        narrative=SARNarrative(
            introduction="[SAR narrative will be generated by the LLM engine]",
            body="[Transaction analysis and 5Ws+How will appear here]",
            conclusion="[Summary and recommendations will appear here]",
        ),
        audit_trail=[
            AuditStep(
                step=1,
                agent="data_analyst",
                action="Placeholder — LLM engine not yet connected",
                data_points_used=[],
                rules_matched=[],
                output="Awaiting LLM integration",
                timestamp=datetime.now().isoformat(),
            )
        ],
        quality_score=QualityScore(),
        status=SARStatus.DRAFT,
    )

    sars_store[sar_id] = sar
    return sar


@router.get("/sar/{sar_id}", response_model=SARResponse, tags=["SAR"])
async def get_sar(sar_id: str):
    """Get a SAR narrative and its audit trail."""
    if sar_id not in sars_store:
        raise HTTPException(status_code=404, detail=f"SAR {sar_id} not found")
    return sars_store[sar_id]


@router.put("/sar/{sar_id}", response_model=SARResponse, tags=["SAR"])
async def update_sar(sar_id: str, request: UpdateSARRequest):
    """Update/edit a SAR narrative (analyst edits)."""
    if sar_id not in sars_store:
        raise HTTPException(status_code=404, detail=f"SAR {sar_id} not found")

    sar = sars_store[sar_id]
    sar.narrative = request.narrative
    sar.status = SARStatus.REVIEW
    sars_store[sar_id] = sar
    return sar


@router.post("/sar/{sar_id}/approve", tags=["SAR"])
async def approve_sar(sar_id: str):
    """Approve a SAR narrative."""
    if sar_id not in sars_store:
        raise HTTPException(status_code=404, detail=f"SAR {sar_id} not found")

    sars_store[sar_id].status = SARStatus.APPROVED
    return {"sar_id": sar_id, "status": "approved", "message": "SAR approved successfully"}


@router.get("/cases", response_model=CaseListResponse, tags=["Cases"])
async def list_cases():
    """List all uploaded cases."""
    items = [
        CaseListItem(
            case_id=cid,
            customer_name=data.get("filename", "Unknown"),
            alert_type="Suspicious Transaction",
            risk_level=RiskLevel.MEDIUM,
            sar_status=SARStatus.DRAFT,
            created_at=data.get("uploaded_at", datetime.now().isoformat()),
        )
        for cid, data in cases_store.items()
    ]
    return CaseListResponse(cases=items, total=len(items))


@router.get("/audit/{sar_id}", tags=["Audit"])
async def get_audit_trail(sar_id: str):
    """Get the full audit trail for a SAR."""
    if sar_id not in sars_store:
        raise HTTPException(status_code=404, detail=f"SAR {sar_id} not found")
    return {"sar_id": sar_id, "audit_trail": sars_store[sar_id].audit_trail}
